### PR TITLE
feat: harmonize colors

### PR DESCRIPTION
**Pull request by martinvibes**
hello @djeck1432 please kindly review :)

### CODE REVIEW

**Comment by djeck1432** [comment]
1. Could you please change color for collateral -> should be green
2. Could you please change color for debt -> should be red 
3. Available liquidity -> `green` 
4. Liquidable debt change please to `red`

**Comment by martinvibes** [comment]
hello @djeck1432 kindly review :)

**Comment by djeck1432** [comment]
Looks good to me

**Review by djeck1432 — APPROVED** [review]

**Comment by martinvibes** [comment]
Alright thank you sir @djeck1432 🚀

**Pull request merged**
