### PR TITLE
Draft PR: Standardize event data parsing (#232)

### PR DESCRIPTION
**Pull request by aniruddhaaps**
### Description
- Added `parse_collateral_enabled_disabled_event` to `ZklendDataParser` for parsing collateral enabled/disabled events into a human-readable format.
- Refactored `process_collateral_disabled_event` to use the new `parse_collateral_enabled_disabled_event` method for improved readability.

### Status
- **WIP**: Requires further testing.
-  2 more issues require addressing.

### CODE REVIEW

**Comment by djeck1432** [comment]
@aniruddhaaps Is that all what you have done during 24 hours? 
If in the morning won't be completed PR you will be unassigned. 
you just kidding me, 3 lines of code

**Comment by djeck1432** [comment]
Sorry, this task is critical, I will unassigned you in 2 hours, if there won't be any further code. 
@aniruddhaaps

**Comment by aniruddhaaps** [comment]
sending another draft in 2hours

**Comment by djeck1432** [comment]
@aniruddhaaps you have 1 hour,if  I won't see enough result, you will be unassigned,

**Comment by aniruddhaaps** [comment]
@djeck1432 I apologize for not being as helpful as I could have been as this was my first odhack. I didn’t fully grasp the urgency of some projects, and I regret any inconvenience caused by my inexperience. I’m committed to improving and will do my best to complete this task within the next 20 hours if it’s reassigned to me

**Comment by djeck1432** [comment]
sorry, this task blocking us, previous contributor didn't manage it, now you can't manage it as well
from my side I wanna say, that you read contributor guideline and text in issue that you would start immediately what didn't happen.

**Comment by djeck1432** [comment]
Even using CHATGPT and have a few examples how to do that you didn't manage. sorry

**Pull request closed without merging**
