### PR TITLE
Refactor: complete serializers reorganization

### LINKED ISSUE #307: Move all events models into separated files
1. Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new folder `serializers` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/handler_tools/data_parser)
3. Move from [serializers.py](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/serializers.py) into separated files (zklend.py and nostra.py)
4. Which serializer where used you can find here:
- [`nostra`](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/nostra.py)
- [`zklend`](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handler_tools/data_parser/zklend.py)
5.  in `serializers` folder, create new file `__init__.py` where you will import all serializers from `zklend.py` and `nostra.py`

### PR DESCRIPTION
**Pull request by akintewe**
Changes Made

- Created new `serializers` folder in `apps/data_handler/handler_tools/data_parser/`
- Separated serializers into two files based on their domain:
- `nostra.py`: Contains Nostra-related serializers
- `zklend.py`: Contains zkLend-related serializers
- Created `__init__.py` with proper imports and exports from both files

Closes #307

### CODE REVIEW

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Please, run `black` command for your files
Remove this file `[get-pip.py](https://github.com/CarmineOptions/derisk-research/pull/317/files#diff-333f925f52b4ce75f65b3e49a8a71acd851ab66561480309d9e34de7a888a452)`

**Comment by akintewe** [comment]
> Please, run `black` command for your files Remove this file `[get-pip.py](https://github.com/CarmineOptions/derisk-research/pull/317/files#diff-333f925f52b4ce75f65b3e49a8a71acd851ab66561480309d9e34de7a888a452)`

Done

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Please, close this pr and create new one, I asked you to run only for files which you have changed, you ran it for all of them. I would be hard to do code review for you code.

**Comment by akintewe** [comment]
> Please, close this pr and create new one, I asked you to run only for files which you have changed, you ran it for all of them. I would be hard to do code review for you code.

oh my bad, got it, ill do that now

**Pull request closed without merging**
