### PR TITLE
test: add test for BaseHealthRatioHandler 

### PR DESCRIPTION
**Pull request by vestor-dev**

### CODE REVIEW

**Comment by djeck1432** [comment]
```
FAILED apps/data_handler/tests/health_ratio_test/test_health_ratio_tests.py::TestBaseHealthRatioHandler::test_initialize_loan_entities - TypeError: Can't instantiate abstract class MockState with abstract method compute_liquidable_debt_at_price
FAILED apps/data_handler/tests/health_ratio_test/test_health_ratio_tests.py::TestBaseHealthRatioHandler::test_initialize_loan_entities_with_empty_data - TypeError: Can't instantiate abstract class MockState with abstract method compute_liquidable_debt_at_price
FAILED apps/data_handler/tests/health_ratio_test/test_health_ratio_tests.py::TestBaseHealthRatioHandler::test_initialize_loan_entities_maintains_existing_state - TypeError: Can't instantiate abstract class MockState with abstract method compute_liquidable_debt_at_price
FAILED apps/data_handler/tests/test_zklend_transformer.py::test_save_collateral_enabled_event - pydantic_core._pydantic_core.ValidationError: 1 validation error for CollateralEnabledDisabledEventData
FAILED apps/data_handler/tests/test_zklend_transformer.py::test_save_collateral_disabled_event - pydantic_core._pydantic_core.ValidationError: 1 validation error for CollateralEnabledDisabledEventData

```

next time If I see that you didn't even test it, I will just unassign you
@vestor-dev

**Comment by vestor-dev** [comment]
holla @djeck1432 i have synced my fork 
kindly review :)

**Comment by djeck1432** [comment]
@vestor-dev Can you please attach screenshot that tests were running succesfully

**Comment by vestor-dev** [comment]
hey @djeck1432 this is it 
image

it works perfectly on mine

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
