### PR TITLE
feat: create test cases for BaseDBLiquidableDebtDataHandler

### LINKED ISSUE #312: Create test cases for BaseDBLiquidableDebtDataHandler
1. Before applying, Read our [Contributor Guidelines](https://github.com/CarmineOptions/derisk-research/blob/master/CONTRIBUTING.md) and [README](https://github.com/CarmineOptions/derisk-research/blob/master/README.md). 
2. Create new folder `liqudation_test` [here](https://github.com/CarmineOptions/derisk-research/tree/master/apps/data_handler/tests)
3. Create positive and negative test cases for [BaseDBLiquidableDebtDataHandler](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/handlers/liquidable_debt/debt_handlers.py)
4. For mocking db connection use fixtures from [confest.py](https://github.com/CarmineOptions/derisk-research/blob/master/apps/data_handler/tests/conftest.py)

### PR DESCRIPTION
**Pull request by kozah04**
resolves #312

### CODE REVIEW

**Review by djeck1432 — CHANGES_REQUESTED** [review]
where are the tests for :
`initialize_loan_entities`
`fetch_data`
?

**Comment by djeck1432** [comment]
@kozah04 you will be unassigned if you not response

**Comment by kozah04** [comment]
Hello @djeck1432, sorry for the delay H
ad some issues with power

**Comment by kozah04** [comment]
I am on it

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
