### PR TITLE
modified & completed Analyze_user_behavior_across_different_lending_protocols.ipynb

### PR DESCRIPTION
**Pull request by tosoham**
Issue #100

### CODE REVIEW

**Comment by lukaspetrasek** [comment]
Hi @tosoham , please check all unresolved comments here https://github.com/CarmineOptions/derisk-research/pull/139 and address them.

Also, please add any new dependencies you need to use to `pyproject.toml` and `poetry.lock` by running `poetry add <package>` 🙏🏼

**Comment by lukaspetrasek** [comment]
Hi @tosoham , it the PR ready again for the review?

**Comment by tosoham** [comment]
Hi @lukaspetrasek , the PR is not ready now I was busy with some other work... will complete it asap.

**Comment by tosoham** [comment]
Hi @lukaspetrasek the PR is ready for review, I have made quite some change and added all the dependencies bt `peotry add `

**Pull request closed without merging**
