### PR TITLE
feat: refactor function call to on-chain

### PR DESCRIPTION
**Pull request by raizo07**

### CODE REVIEW

**Review by djeck1432 — CHANGES_REQUESTED** [review]
@raizo07  What about imports in the `data_handler`?

**Comment by djeck1432** [comment]
@raizo07 What about imports in the data_handler?

**Comment by raizo07** [comment]
> @raizo07 What about imports in the data_handler?

On this now

**Comment by djeck1432** [comment]
@raizo07 Please, resolve confict

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Looks good to me, just resolve conflict

**Comment by raizo07** [comment]
@djeck1432 Done.

**Review by djeck1432 — APPROVED** [review]
Looks good to me

**Pull request merged**
