### PR TITLE
feat/issue-#288

### PR DESCRIPTION
**Pull request by ekumamatthew**
issue #288

### CODE REVIEW

**Comment by djeck1432** [comment]
Please, sync with master @ekumamatthew

**Comment by djeck1432** [comment]
Screenshot 2024-11-24 at 12 11 41
Do not work in master branch in your fork, next time create new branch from master

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Screenshot 2024-11-24 at 17 15 37
Did you run it?

**Comment by ekumamatthew** [comment]
dbtest

the test passed on my local

**Pull request merged**
